In [1]:
import numpy as np

In [26]:
def row_op(A, op):    
    op = np.array(op)
    for i, j in op:
        A[j] = (A[i] + A[j]) % 2
    return A

In [44]:
A = np.identity(7)

A[1, 2] = A[1, 4] = 1
A[3, 1] = 1
A[4, 1] = A[4, 2] = A[4, 3] = A[4, 5] = 1
A[5, 1] = A[5, 3] = 1
A[6, 1] = A[6, 3] = 1

A_init = A.copy()


# print(A[1:, 1:])

# A = row_op(A, [[4, 1]])


Y1 = []

y = [[6, 3], [5, 6], [4, 5], [1, 4]]
A = row_op(A, y)
Y1.extend(y)

y = [[2, 5]]
A = row_op(A, y)
Y1.extend(y)

y = [[4, 5], [5, 6], [6, 3]]
A = row_op(A, y)
Y1.extend(y)

y = [[5, 4], [6, 5], [3, 6]]
A = row_op(A, y)
Y1.extend(y)

A = A.transpose()

Y2 = []
y = [[1, 2], [1, 4]]
A = row_op(A, y)
Y2.extend(y)

y = [[5, 4], [6, 5], [3, 6], [6, 5], [5, 4], [6, 5], [3, 6], [6, 5]]
A = row_op(A, y)
Y2.extend(y)

y = [[5, 6]]
A = row_op(A, y)
Y2.extend(y)


print(A[1:, 1:])

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [46]:
id = np.identity(7)
id = row_op(id, [[j,i] for i, j in Y2])
id = row_op(id, Y1[::-1])
print(id)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0. 1.]]


In [47]:
A_init

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 1.]])

In [62]:
identity = np.identity(9)
op1 = np.array([[5, 2],[2, 1], [5, 2], [2,1]])-1

op2 = np.array([[4, 5], [5, 6], [9, 6], [6, 3], [5, 6], [9, 6], 
        [4, 5], [5, 6], [6,3], [5, 6]])-1

op3 = np.array([[5,6], [6, 9], [5, 6]])-1

op4 = np.array([[4, 5], [5, 6], [6, 9], [5, 6], [4, 5]])-1


In [63]:
upper = np.identity(9)
for i, j in op1:
    upper[j] = (upper[i] + upper[j]) % 2

for i, j in op2:
    upper[j] = (upper[i] + upper[j]) % 2

for i, j in op3:
    upper[j] = (upper[i] + upper[j]) % 2

for i, j in op4:
    upper[j] = (upper[i] + upper[j]) % 2

upper

array([[1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [68]:
parity = np.identity(9)
parity[0,4]= parity[2,3]=parity[2,8]=parity[8,3] = 1
parity

array([[1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [50]:
upper = parity.copy()

for i, j in op4[::-1]:
    upper[j] = (upper[i] + upper[j]) % 2

for i, j in op3[::-1]:
    upper[j] = (upper[i] + upper[j]) % 2

upper

array([[1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [67]:

opin = np.array([[8,2], [4,0], [3,8]])
parity = np.identity(9)
for i, j in opin:
    parity[j] = (parity[i] + parity[j]) % 2
parity

array([[1., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1.]])